### ISSUE TITLE
Unicron Starting Cause ActiveRecord::AdapterNotSpecified Specified error

### ISSUE THREAD

**Issue by nazarhussain** [sosedoff/capistrano-unicorn#35]
Here is my `unicorn.rb` code

``` ruby
app_path = "/home/deploy/apps/local.myapp.com/myapp/current"

# Set unicorn options
worker_processes 1
preload_app true
timeout 180

listen "#{app_path}/tmp/pids/unicorn.sock", backlog: 1024
pid    "#{app_path}/tmp/pids/unicorn.pid"

# Spawn unicorn master worker for user apps (group: apps)

# Fill path to your app
working_directory app_path

# Should be 'production' by default, otherwise use other env 
rails_env = 'local'

# Log everything to one file
stderr_path "log/unicorn.log"
stdout_path "log/unicorn.log"

before_fork do |server, worker|
  ActiveRecord::Base.connection.disconnect!

  old_pid = "#{server.config[:pid]}.oldbin"
  if File.exists?(old_pid) && server.pid != old_pid
    begin
      Process.kill("QUIT", File.read(old_pid).to_i)
    rescue Errno::ENOENT, Errno::ESRCH
      # someone else did our job for us
    end
  end
end

after_fork do |server, worker|
  ActiveRecord::Base.establish_connection
end
```

When I use capistrano command `cap local unicorn:start` it cause this error:

```
/home/deploy/apps/local.myapp.com/myapp/shared/bundle/ruby/1.9.1/gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/connection_specification.rb:62:in `establish_connection': current database is not configured (ActiveRecord::AdapterNotSpecified)
    from /home/deploy/apps/local.myapp.com/myapp/shared/bundle/ruby/1.9.1/gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/connection_specification.rb:55:in `establish_connection'
    from /home/deploy/apps/local.myapp.com/myapp/shared/bundle/ruby/1.9.1/gems/activerecord-3.0.3/lib/active_record/railtie.rb:59:in `block (2 levels) in <class:Railtie>'
    from /home/deploy/apps/local.myapp.com/myapp/shared/bundle/ruby/1.9.1/gems/activesupport-3.0.3/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
    from /home/deploy/apps/local.myapp.com/myapp/shared/bundle/ruby/1.9.1/gems/activesupport-3.0.3/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
    from /home/deploy/apps/local.myapp.com/myapp/shared/bundle/ruby/1.9.1/gems/activesupport-3.0.3/lib/active_support/lazy_load_hooks.rb:26:in `on_load'
    from /home/deploy/apps/local.myapp.com/myapp/shared/bundle/ruby/1.9.1/gems/activerecord-3.0.3/lib/active_record/railtie.rb:57:in `block in <class:Railtie>'
    from /home/deploy/apps/local.myapp.com/myapp/shared/bundle/ruby/1.9.1/gems/railties-3.0.3/lib/rails/initializable.rb:25:in `instance_exec'
    from /home/deploy/apps/local.myapp.com/myapp/shared/bundle/ruby/1.9.1/gems/railties-3.0.3/lib/rails/initializable.rb:25:in `run'
    from /home/deploy/apps/local.myapp.com/myapp/shared/bundle/ruby/1.9.1/gems/railties-3.0.3/lib/rails/initializable.rb:50:in `block in run_initializers'
    from /home/deploy/apps/local.myapp.com/myapp/shared/bundle/ruby/1.9.1/gems/railties-3.0.3/lib/rails/initializable.rb:49:in `each'
    from /home/deploy/apps/local.myapp.com/myapp/shared/bundle/ruby/1.9.1/gems/railties-3.0.3/lib/rails/initializable.rb:49:in `run_initializers'
    from /home/deploy/apps/local.myapp.com/myapp/shared/bundle/ruby/1.9.1/gems/railties-3.0.3/lib/rails/application.rb:134:in `initialize!'
    from /home/deploy/apps/local.myapp.com/myapp/shared/bundle/ruby/1.9.1/gems/railties-3.0.3/lib/rails/application.rb:77:in `method_missing'
    from /home/deploy/apps/local.myapp.com/myapp/releases/20121110235022/config/environment.rb:8:in `<top (required)>'
```

Where as if I run this command from bash console on the server it works pretty fine. 

```
 BUNDLE_GEMFILE=/home/deploy/apps/local.myapp.com/myapp/current/Gemfile bundle exec unicorn -c /home/deploy/apps/local.myapp.com/myapp/current/config/unicorn/local.rb -E local -D
```

Due to this issue my deployment process is struck. Please look into this issue and guide me.

**Comment by sosedoff** [comment]
Do you have a `local` section in `database.yml` ?

**Comment by nazarhussain** [comment]
Yes I do have. That's why the direct command works fine.

**Comment by sosedoff** [comment]
Can you show your `deploy.rb` config? (remove all private info)

**Comment by nazarhussain** [comment]
Here it is:

``` ruby
set :rvm_ruby_string, '1.9.3'
set :rvm_type, :system
set :application, "my_app"
set :user, "deploy"
set :deploy_via, :remote_cache
set :use_sudo, true
set :scm, :git
set :repository, "git@github.com:myapp/myapp_repo.git"
set :whenever_command, "bundle exec whenever"
set :default_run_options, :pty => true
set :ssh_options, :forward_agent => true
default_run_options[:pty] = true
ssh_options[:forward_agent] = true
default_environment["RAILS_ENV"] = 'current'
set :filter_sensitive_settings, []

[:local, :current, :production].each do |config|
  task config do
    set :host, {
        production: 'app.myapp.com',
        current: 'current.myapp.com',
        local: 'local.myapp.com',
    }[config]
    set :branch, {
        production: 'production'.to_sym,
        current: 'master'.to_sym,
        local: 'deployment-chef-cap'.to_sym
    }[config]
    set :deploy_to, "/home/deploy/apps/#{host}/#{application}"
    set :rails_env, config
    role :web, host # some tasks require this role
    role :app, host # "
    role :db, host, primary: true
    set :cap_env, config

    # Chef
    ## mysql cookbook
    set :mysql,
        :server_root_password => p = {production: 'password', staging: 'password', local: 'password'}[config],
        :server_debian_password => p,
        :server_repl_password => p

    ## meeting_king cookbook
    set :my_app,
        user: 'deploy',
        group: 'developers',
        developers: %w"dev1 dev2 dev2"
  end
end

## Chef
set :nginx, :worker_processes => 4


require 'roundsman/capistrano'
require 'capistrano_colors'
require 'bundler/capistrano'
require 'capistrano-unicorn'
require 'whenever/capistrano'
require 'delayed/recipes'
require 'thinking_sphinx/deploy/capistrano'
require 'airbrake/capistrano'

def remote_file_exists?(full_path)
  'true' == capture("if [ -e #{full_path} ]; then echo 'true'; fi").strip
end

before 'deploy:update_code' do # before code checkout (also applies to migrations)
  if roundsman.install.install_ruby?
    unless remote_file_exists?('/usr/sbin/apt-fast')
      run %Q(
      # install apt-fast which enables parallel connections
      #{sudo} wget -O /usr/sbin/apt-fast https://raw.github.com/ilikenwf/apt-fast/master/apt-fast; \
          #{sudo} chmod +x /usr/sbin/apt-fast; \
          #{sudo} apt-get install axel; \
          #{sudo} sed -i -e"s/#_DOWNLOADER='cat/_DOWNLOADER='cat/" /usr/sbin/apt-fast;
      )
    end
    roundsman.install.dependencies
    roundsman.install.ruby
  end
  set :run_list, [
      'recipe[myapp::before_recipes]',
      'recipe[myapp::before_code]'
  ]
  roundsman.run_chef
end

before 'deploy:migrate' do # before migrations run
  roundsman.run_list [
                         'recipe[myapp::before_recipes]',
                         'recipe[mysql::client]',
                         'recipe[mysql::server]',
                         'recipe[myapp::before_migrate]'
                     ]
end
after 'deploy:create_symlink' do # after code checkout
  roundsman.run_list [
                         'recipe[myapp::before_recipes]',
                         'recipe[nginx]',
                         'recipe[myapp::after_code]'
                     ]
end

```

**Comment by nazarhussain** [comment]
I also tried to comment out the `before_fork` and `after_fork` block, but it still have the same issue.

**Comment by nazarhussain** [comment]
I found the issue. 

I was setting `default_environment["RAILS_ENV"] = 'current'` outside the environment configuration block. So why Unicorn was always loading `current` environment. Whereas I was using `local` environment configuration in `database.yml`.  

Setting      `default_environment["RAILS_ENV"] = config.to_s` inside configuration block solved the issue.
