### ISSUE TITLE
config.eager_load is set to nil

### ISSUE THREAD

**Issue by kyledecot** [sosedoff/capistrano-unicorn#84]
I'm attempting to run `bundle exec unicorn -c /var/www/skateboxes/current/config/unicorn/production.rb -E deployment` which is what  `cap production unicorn:start` runs. I get the following output: 

```
INFO -- : Refreshing Gem list
config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:

  * development - set it to false
  * test - set it to false (unless you use a tool that preloads your test environment)
  * production - set it to true

I, [2013-10-25T00:57:12.607520 #7233]  INFO -- : unlinking existing socket=/tmp/unicorn.skateboxes.sock
I, [2013-10-25T00:57:12.607950 #7233]  INFO -- : listening on addr=/tmp/unicorn.skateboxes.sock fd=10
E, [2013-10-25T00:57:12.851888 #7233] ERROR -- : database configuration does not specify adapter (ActiveRecord::AdapterNotSpecified)
/var/www/skateboxes/shared/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/connection_specification.rb:52:in `resolve_hash_connection'
/var/www/skateboxes/shared/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/connection_specification.rb:46:in `resolve_string_connection'
/var/www/skateboxes/shared/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/connection_specification.rb:30:in `spec'
/var/www/skateboxes/shared/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_handling.rb:39:in `establish_connection'
/var/www/skateboxes/shared/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/railtie.rb:175:in `block (2 levels) in <class:Railtie>'
/var/www/skateboxes/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/var/www/skateboxes/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/var/www/skateboxes/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/var/www/skateboxes/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/lazy_load_hooks.rb:44:in `each'
/var/www/skateboxes/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/var/www/skateboxes/shared/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/base.rb:322:in `<module:ActiveRecord>'
/var/www/skateboxes/shared/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/base.rb:22:in `<top (required)>'
/var/www/skateboxes/current/config/unicorn/production.rb:28:in `block in reload'
/var/www/skateboxes/shared/bundle/ruby/2.0.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:495:in `call'
/var/www/skateboxes/shared/bundle/ruby/2.0.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:495:in `spawn_missing_workers'
/var/www/skateboxes/shared/bundle/ruby/2.0.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:142:in `start'
/var/www/skateboxes/shared/bundle/ruby/2.0.0/gems/unicorn-4.6.3/bin/unicorn:126:in `<top (required)>'
/var/www/skateboxes/shared/bundle/ruby/2.0.0/bin/unicorn:23:in `load'
/var/www/skateboxes/shared/bundle/ruby/2.0.0/bin/unicorn:23:in `<main>'
```

My production config definitely has this set to true. I fee like this has something to do w/ the -E flag. If I sent this to `production` then the error disappears and my app starts.

**Comment by rbrancher** [comment]
Any insight on this?
I have the same error, but on production environment and randomly.

**Comment by ezmiller** [comment]
Any solution to this error?

**Comment by tboyko** [comment]
+1

**Comment by mitsuihinsuke** [comment]
+1

**Comment by shawndeprey** [comment]
+1 Running into the same issue running Rails 4.2 on Ruby 2.2 on heroku.

**Comment by roamabit** [comment]
+1 
4.2, 2.2, Jruby, heroku, incorrect server shutdown sequence. haven;t been able to fix yet.

**Comment by wooodyhuang** [comment]
I got the same issue when set up Redmine3.0.3 with Ruby2.1.5/Rails4.2.1/Unicorn4.9.0
